language: elixir
otp_release: 19.2
elixir: 1.4.0
sudo: false
before_script:
  - mix deps.get
  - MIX_ENV=test mix compile --warnings-as-errors
  - MIX_ENV=prod mix compile --warnings-as-errors
  - nvm install 6.9 && nvm use 6.9
  - MIX_ENV=test mix frontend.install
script:
  - mix test
  - MIX_ENV=test mix lint
  - MIX_ENV=prod mix release --warnings-as-errors --env=prod
after_success:
  - bash .ci/docs.sh
env:
  global:
    secure: "rUK3Io25QPvBdh31RRz9h480R5b3RlSNUqo15My7ZTP9UccO7OG1zlSCwlQxg5/Pvq+AQ3hnlqhXpBfNOylBBM0HSKlf05lm3+XsgmYy/zcQ/3n6xwVyPJMYUgPOj3Fpc3YA3RDAULSaYJ4BzuAdpA/tjOZAADgOLMpl/uWl7359zT+t10BjR/fMA6FTWPXWb/euiHA+bloiNnb4HkAvBHGaokTeaCD/nyQ1igOdiQO13Jq1yJLCs7T8nn83jInGg0XPrXIXNktDEQzh9Eb9nftk68AH+Pj2ejspUmZ4ju20s3fFc4jBg0o+dUZWuFFiDjo5f69VRdEs7vXpFMhtjLKFrYrHTe8TlipaR6odlWgTHHw+nbcUNcASID7OQowSX5fMdZNalwauaiuR1Ddl/VMJaNmh2vfUt1SurxHlRPK4at+V2J5AojWTSerFCi4q+X9zIv+w68zR9TGQOPqMfz9gwEu0wkflT6D1dAM2IswXBoZ02juBzxFpQVIejNheBt6bsPIGJ/NYIMC5RqPJvDipVcmOQZyy5Crro0CxcBfhGhP+sm/Owu8peLjecpcVSPq4mEKeSgVPHRCyAXysN3F7en0f/3EilaZYOeXXYInWs5MUH1rjaG4NPO93M3saKtqDScVKp79N/jyGAP9NQ8OfpkmyUAg1fZJhpiKRTlI="
