language: elixir
matrix:
  include:
    - otp_release: 18.3
      elixir: 1.3.4
    - otp_release: 19.0
      elixir: 1.3.4
sudo: false
before_script:
  - mix deps.get
  - MIX_ENV=test mix compile
  - MIX_ENV=prod mix compile
  - nvm install 6.9 && nvm use 6.9
  - mix frontend.install
script:
  - mix test
  - MIX_ENV=test mix lint
  - MIX_ENV=prod mix release --warnings-as-errors --env=prod
